-- CRE workflow executions started by pull_request webhooks.
-- cre-runner inserts a row per (delivery, active campaign of the repo) and updates it as it runs:
-- queued -> running -> completed | failed | skipped.
create table if not exists public.cre_executions (
    id                   uuid        primary key,                 -- CRE execution id, generated by cre-runner
    delivery_id          text        not null,                    -- X-GitHub-Delivery of the triggering webhook
    campaign_id          uuid        not null references public.campaigns (id),
    repository_full_name text        not null,
    pr_number            integer     not null,
    event                text        not null check (event in ('opened', 'merged')),
    head_sha             text,                                    -- commit the evaluation is pinned to
    status               text        not null default 'queued'
                                     check (status in ('queued', 'running', 'completed', 'failed', 'skipped')),
    request              jsonb       not null,                    -- HTTP trigger payload sent to the workflow
    score                integer,
    eligible             boolean,
    reward               text,                                    -- token base units, e.g. "445000000" = 445 USDC
    evaluation_hash      text,
    policy_hash          text,
    settled              boolean     not null default false,      -- eligible merged result that pays out
    error                text,                                    -- failure or skip reason
    runner_instance      text,                                    -- machine that ran it (Fly machine id)
    created_at           timestamptz not null default now(),
    started_at           timestamptz,
    finished_at          timestamptz
);

-- One payout per (campaign, repo, PR), even across runner machines.
create unique index if not exists cre_executions_settled_uniq
    on public.cre_executions (campaign_id, repository_full_name, pr_number) where settled;

create index if not exists cre_executions_delivery_idx
    on public.cre_executions (delivery_id);
create index if not exists cre_executions_repo_pr_idx
    on public.cre_executions (repository_full_name, pr_number, created_at desc);
create index if not exists cre_executions_campaign_idx
    on public.cre_executions (campaign_id, created_at desc);
create index if not exists cre_executions_unfinished_idx
    on public.cre_executions (runner_instance) where status in ('queued', 'running');

-- No policies: only the service role / secret key (used by cre-runner) can access this table.
alter table public.cre_executions enable row level security;
