"use client"

import { PrivyProvider } from "@privy-io/react-auth"
import { createSolanaRpc, createSolanaRpcSubscriptions } from "@solana/kit"
import { useTheme } from "next-themes"

import { SOLANA_CHAIN, SOLANA_RPC_URL } from "@/lib/contrib-oracle"

export const PRIVY_APP_ID = process.env.NEXT_PUBLIC_PRIVY_APP_ID

// Privy sends and confirms the transactions users sign (campaign creation, funding).
const solanaRpcs = {
  [SOLANA_CHAIN]: {
    rpc: createSolanaRpc(SOLANA_RPC_URL),
    rpcSubscriptions: createSolanaRpcSubscriptions(
      SOLANA_RPC_URL.replace(/^http/, "ws")
    ),
    blockExplorerUrl: "https://explorer.solana.com",
  },
}

// Sign in with GitHub through Privy; every user gets a Solana embedded wallet. Contributors
// whose PRs were merged before they signed in already have one, pregenerated by cre-runner
// from their GitHub account, and get that same wallet on sign-in.
export function WalletProvider({ children }: { children: React.ReactNode }) {
  const { resolvedTheme } = useTheme()
  if (!PRIVY_APP_ID) return children

  return (
    <PrivyProvider
      appId={PRIVY_APP_ID}
      config={{
        loginMethods: ["github"],
        appearance: {
          walletChainType: "solana-only",
          theme: resolvedTheme === "dark" ? "dark" : "light",
        },
        embeddedWallets: {
          ethereum: { createOnLogin: "off" },
          solana: { createOnLogin: "users-without-wallets" },
        },
        solana: { rpcs: solanaRpcs },
      }}
    >
      {children}
    </PrivyProvider>
  )
}
