[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
contrib_oracle = "FSy2V61Tvm6bVHV4dGtoJS7T16eE7ZNjvGHEyT3aw6MA"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
